c3s-magic/c3s-magic-wps

c3s_magic_wps/processes/wps_zmnam.py, c3s_magic_wps/templates/esmvaltool/recipe_zmnam.yml.j2
This PR fixes c3s-magic/c3s-magic-metric-status/issues/6
Changes:
* Updated Recipe
* Updated metadata
=> ZMNAM Diagnostic

c3s_magic_wps/processes/wps_teleconnections.py, c3s_magic_wps/templates/esmvaltool/recipe_miles_eof.yml.j2
This PR fixes miles teleconnections recipe (EOF)
Changes:
```
commit 53847e43758eb525bebb0e527c466eb7c203581d
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Mon May 6 15:38:54 2019 +0200
update documentation link
commit 12bbe5bbddcf227d27fbad57c1950014b633aeca
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Mon May 6 15:37:33 2019 +0200
remove field key for miles_eof recipe
```
=> Miles teleconnections recipe

c3s_magic_wps/processes/wps_shapeselect.py, c3s_magic_wps/templates/esmvaltool/recipe_shapeselect.yml.j2
This PR fixes the shape selection recipe template
Changes:
* remove field key from shapeselect recipe template
=> remove field key from shapeselect recipe template

c3s_magic_wps/processes/wps_consecdrydays.py, c3s_magic_wps/templates/esmvaltool/recipe_consecdrydays.yml.j2
This PR fixes consecutive dry days WPS template
Changes:
* Removed field key from template file
=> consecutive dry days

c3s_magic_wps/processes/wps_ensclus.py, c3s_magic_wps/static/diagnosticsdata/ensclus/ensclus.yml, c3s_magic_wps/templates/esmvaltool/recipe_ensclus.yml.j2
This PR fixes ensemble clustering
Changes:
```
commit d44365b55b2e4e6f5496270a6be69e3c19b2a7d6
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Mon May 6 14:22:34 2019 +0200
number of PCs is an integer
commit 535d8bd493dbba5b5603e8f528be3b4fc1c5f6be
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Mon May 6 14:22:12 2019 +0200
remove field key; fix interpolation type; fix input options
commit b724e7548ea1e58f06272df4af55b14c0cad13f1
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Mon May 6 14:21:06 2019 +0200
add number of PCs as input variable
```
=> Ensclus update

c3s_magic_wps/processes/wps_weather_regimes.py, c3s_magic_wps/templates/esmvaltool/recipe_miles_regimes.yml.j2
This PR fixes c3s-magic/c3s-magic-metric-status/issues/16
Changes:
* Fixed Recipe
=> Removed field from recipe

c3s_magic_wps/processes/wps_multimodel_products.py, c3s_magic_wps/processes/wps_shapeselect.py, c3s_magic_wps/templates/esmvaltool/recipe_multimodel_products_wp5.yml.j2, c3s_magic_wps/templates/esmvaltool/recipe_shapeselect.yml.j2
Added weighting method to inputs
=> Shapeselect

c3s_magic_wps/processes/wps_heatwaves_coldwaves.py, c3s_magic_wps/templates/esmvaltool/recipe_heatwaves_coldwaves_wp7.yml.j2
This PR fixes heatwaves_coldwaves diagnostic
Changes:
```
commit 773a5d36b8c77281dc3a792d612d4b103f53c853 (HEAD -> heatwaves_coldwaves, origin/heatwaves_coldwaves)
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Tue May 14 14:33:12 2019 +0200
update timing; experiment type for historical member is fixed, remove it from input
commit 3c7e57dcf79c9731b396cb62dca8d11150bf9ce9
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Tue May 14 14:32:24 2019 +0200
set historical experiment to type historical, else diagnostic will fail; note projection experiment cannot be of type historical, else diagnostic will fail
commit a64ea773057824d1713676929b8a50125ff82bcf
Author: Ronald van Haren <r.vanharen@esciencecenter.nl>
Date:   Thu May 9 16:50:21 2019 +0200 …
```
=> Heatwaves coldwaves

c3s_magic_wps/cli.py, c3s_magic_wps/processes/utils/__init__.py, c3s_magic_wps/processes/utils/esmvaltool_utils.py, c3s_magic_wps/processes/wps_preproc_example.py, c3s_magic_wps/runner.py
Add outputs to preproc example
=> Added all outputs to preproc example

README.rst, docs/source/index.rst, docs/source/processes.rst, readthedocs.yml
Fixed readthedocs setup by pinning to Python 3.6
=> Readthedocs fix

c3s_magic_wps/processes/wps_quantilebias.py
=> Quantilebias

c3s_magic_wps/processes/wps_rainfarm.py
This PR fixes Rainfarm
Changes:
* Added ...
=> rainfarm: add max_occurs=1

c3s_magic_wps/processes/wps_weather_regimes.py, c3s_magic_wps/templates/esmvaltool/recipe_miles_regimes.yml.j2
=> Weather regimes

c3s_magic_wps/processes/wps_shapeselect.py, c3s_magic_wps/templates/esmvaltool/recipe_shapeselect.yml.j2
This PR fixes shapefile_selection
Changes:
* Added ...
=> Shapefile selection

c3s_magic_wps/processes/wps_consecdrydays.py, c3s_magic_wps/templates/esmvaltool/recipe_consecdrydays.yml.j2
This PR fixes consecdrydays
Changes:
* Added ...
=> Consecutive drydays

c3s_magic_wps/processes/wps_drought_indicator.py, c3s_magic_wps/templates/esmvaltool/recipe_spei.yml.j2
* Added max_occurs=1
* Fixed reference model setting in recipe
=> Drought Indicator

c3s_magic_wps/processes/wps_modes_variability.py, c3s_magic_wps/templates/esmvaltool/recipe_modes_of_variability.yml.j2
This PR fixes Modes of variability
=> Modes of variability

c3s_magic_wps/processes/wps_cvdp.py, c3s_magic_wps/templates/esmvaltool/recipe_cvdp.yml.j2
=> update to cvdp

c3s_magic_wps/processes/__init__.py, c3s_magic_wps/processes/wps_perfmetrics.py, c3s_magic_wps/runner.py, c3s_magic_wps/templates/esmvaltool/recipe_perfmetrics_CMIP5.yml.j2, tests/test_wps_caps.py
Perfmetrics implementation.
I am unable to succesfully test this. Using canary to call the process it does not start for some reason. Using birdy it does start but hangs. @rvanharen can you try this branch.
=> Perfmetrics

c3s_magic_wps/processes/__init__.py, c3s_magic_wps/processes/wps_extreme_events.py, c3s_magic_wps/templates/esmvaltool/recipe_extreme_events.yml.j2, tests/test_wps_caps.py
This PR adds WPS process for extreme events metric
tested with:
canary execute extreme_events --start-year 1980 --end-year 1983 --model MPI-ESM-MR IPSL-CM5A-MR --experiment historical historical --ensemble r1i1p1 r1i1p1
=> Extreme events

c3s_magic_wps/processes/wps_ensclus.py
This PR fixes issues mentioned in https://github.com/c3s-magic/c3s-magic-metric-status/issues/12
Changes:
* make number of PCs an integer field
* fix typo
=> Ensclus fix

c3s_magic_wps/processes/wps_rainfarm.py
This PR makes some changes as per comments in https://github.com/c3s-magic/c3s-magic-metric-status/issues/23
- set default slope to 0
- hardcode weights climo option to false
=> Rainfarm fix

c3s_magic_wps/processes/wps_hyint.py
This PR fixes issues listed in https://github.com/c3s-magic/c3s-magic-metric-status/issues/8
=> Hyint fixes

c3s_magic_wps/processes/wps_ensclus.py, c3s_magic_wps/templates/esmvaltool/recipe_ensclus.yml.j2
https://github.com/c3s-magic/c3s-magic-metric-status/issues/12\#issuecomment-495521762
=> make variable selectable, support pr and tas

c3s_magic_wps/processes/wps_blocking.py, c3s_magic_wps/processes/wps_teleconnections.py, c3s_magic_wps/processes/wps_weather_regimes.py
Updated default model for miles metrics
=> Updated default model for miles metrics

c3s_magic_wps/processes/wps_extreme_events.py, c3s_magic_wps/processes/wps_smpi.py
=> Small fixes

c3s_magic_wps/processes/wps_ensclus.py
As requested in https://github.com/c3s-magic/c3s-magic-metric-status/issues/12#issuecomment-498690781
=> Set min_occurs=3 for number of models to show in ensclus

.travis.yml, Dockerfile, docker-compose.yml, environment.yml, etc/magic-docker.cfg.j2
Tuning pywps for less connection problems, switched to pywps development version
=> Pywps tuning: Development pywps and some server settings

c3s_magic_wps/processes/wps_ensclus.py
=> Added variable to options for jinja2 template

c3s_magic_wps/processes/wps_capacity_factor.py
Changed defaults for capacity factor
=> Changed defaults for capacity factor

c3s_magic_wps/processes/utils/data_finder.py
=> added capability to cache file metadata

.travis.yml, Dockerfile, docs/source/installation.rst, environment.yml
This PR fixes #84
Changes:
* Added ...
=> Update dockerfile to use conda esmvaltool package

c3s_magic_wps/processes/wps_blocking.py, c3s_magic_wps/processes/wps_capacity_factor.py, c3s_magic_wps/processes/wps_combined_indices.py, c3s_magic_wps/processes/wps_consecdrydays.py, c3s_magic_wps/processes/wps_cvdp.py, c3s_magic_wps/processes/wps_diurnal_temperature_index.py, c3s_magic_wps/processes/wps_drought_indicator.py, c3s_magic_wps/processes/wps_ensclus.py, c3s_magic_wps/processes/wps_extreme_events.py, c3s_magic_wps/processes/wps_extreme_index.py, c3s_magic_wps/processes/wps_heatwaves_coldwaves.py, c3s_magic_wps/processes/wps_hyint.py, c3s_magic_wps/processes/wps_modes_variability.py, c3s_magic_wps/processes/wps_multimodel_products.py, c3s_magic_wps/processes/wps_perfmetrics.py, c3s_magic_wps/processes/wps_preproc_example.py, c3s_magic_wps/processes/wps_quantilebias.py, c3s_magic_wps/processes/wps_rainfarm.py, c3s_magic_wps/processes/wps_shapeselect.py, c3s_magic_wps/processes/wps_smpi.py, c3s_magic_wps/processes/wps_teleconnections.py, c3s_magic_wps/processes/wps_toymodel.py, c3s_magic_wps/processes/wps_weather_regimes.py, c3s_magic_wps/processes/wps_zmnam.py
This PR fixes #80 
Changes:
* Added ...
=> use workdir for wps outputs #80

c3s_magic_wps/processes/utils/esmvaltool_utils.py
allow for optional end_year in year_ranges and reference_year_ranges function
=> allow for optional end_year in year_ranges and reference_year_ranges
